spring.application.name=ecom-mcp-client

server.port=8081

spring.ai.openai.api-key= ${OPEN_AI_API_KEY}
spring.ai.mcp.client.sse.connections.ecom-server.url=http://localhost:8080
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile